package operador;

import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Conector;

public class GenerarServicio extends javax.swing.JFrame {

    String dia = "dia";
    String mes = "mes";
    String annio = "annio";

    public GenerarServicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        colocarFecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReporte = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtVehiculo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generar Servicio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtReporte.setColumns(20);
        txtReporte.setRows(5);
        jScrollPane1.setViewportView(txtReporte);

        jLabel2.setText("Vehículo");

        jLabel3.setText("Fecha");

        txtFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtFecha.setText("00-00-00");

        jLabel5.setText("Hora");

        txtHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtHora.setText("00:00");

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("De:");

        txtPropietario.setText("N");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVehiculo)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPropietario)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPropietario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtFecha)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtHora)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGenerar)
                            .addComponent(jButton2))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Se instancia una conexion de la clase conecta
    Conector con = new Conector();
    // se asigna la conexion a la base de datos con la variable cn
    Connection cn = con.conecta();
    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        txtVehiculo.setText(txtVehiculo.getText().toUpperCase());
        //buscamos si el auto no esta en servicio
        if (txtVehiculo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "te faltan campos por llenar");
            txtVehiculo.setText("");
            txtVehiculo.requestFocus();
        } else if (txtReporte.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "te faltan campos por llenar");
            txtReporte.setText("");
            txtReporte.requestFocus();
        } else {

            int contador = 0;
            String estado = "no";
            String marca = "marca";
            String placa = "placa";
            String modelo = "modelo";
            String tipo = "tipo";
            try {
                Statement st;
                st = cn.createStatement();
                String sql = "SELECT * FROM vehiculo WHERE numero='" + txtVehiculo.getText() + "'";
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    contador++;
                    estado = rs.getString("activo");
                    marca = rs.getString("marca");
                    placa = rs.getString("placa");
                    modelo = rs.getString("modelo");
                    tipo = rs.getString("tipo");

                }
            } catch (SQLException ex) {
                Logger.getLogger(GenerarServicio.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (contador == 0) {
                JOptionPane.showMessageDialog(this, "El vehiculo no se encuentra en el listado");
                txtVehiculo.setText("");
                txtVehiculo.requestFocus();
            } else if (estado.equals("no")) {
                JOptionPane.showMessageDialog(this, "El vehiculo se encuentra en servicio");
                txtVehiculo.setText("");
                txtVehiculo.requestFocus();
            } else {
                String mensaje = "Se va a generar el reporte\npara el vehiculo\nNumero " + txtVehiculo.getText()
                        + " Placa: " + placa + "\nTipo: " + tipo + " Modelo: " + modelo
                        + "\nMarca: " + marca;
                int respuesta = JOptionPane.showConfirmDialog(this, mensaje, "Confirmación", JOptionPane.YES_NO_OPTION);
                if (respuesta == JOptionPane.YES_OPTION) {
                    //procedemos a grabar el el servicio
                    String genero = txtPropietario.getText();
                    String vehiculo = txtVehiculo.getText();
                    String reporte = txtReporte.getText();
                    String hora = txtHora.getText();
                    java.sql.Date fecha = (java.sql.Date) fechaMysql();
                    String sql = "INSERT INTO servicio (genero,vehiculo,reporte,fecha,hora,estado) VALUES (?,?,?,?,?,?)";

                    try {
                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.setString(1, genero);
                        pst.setString(2, vehiculo);
                        pst.setString(3, reporte);
                        pst.setDate(4, fecha);
                        pst.setString(5, hora);
                        pst.setString(6, "enviado");
                        pst.executeUpdate();

                        //actualizamos vehiculo
                        Statement st;
                        st = cn.createStatement();
                        sql = "UPDATE vehiculo set activo='no' where numero='" + vehiculo + "'";
                        st.executeUpdate(sql);

                        JOptionPane.showMessageDialog(this, "El servicio esta\ncorrectamente generado");
                        operador.Principal frm = new operador.Principal();
                        frm.setVisible(true);
                        operador.Principal.txtNombre.setText(genero);
                        this.dispose();
                    } catch (SQLException ex) {
                        Logger.getLogger(GenerarServicio.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            operador.Principal frm = new operador.Principal();
            frm.setVisible(true);
            operador.Principal.txtNombre.setText(txtPropietario.getText());
            this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    Date fechaMysql() {
        String fechaMysql = annio + "/" + mes + "/" + dia;
        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
        try {
            Date parsed = formato.parse(fechaMysql);
            java.sql.Date sqlFecha = new java.sql.Date(parsed.getTime());
            return sqlFecha;
        } catch (ParseException ex) {
            Logger.getLogger(GenerarServicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    private void colocarFecha() {
        Calendar c = Calendar.getInstance();
        dia = Integer.toString(c.get(Calendar.DATE));
        mes = Integer.toString(c.get(Calendar.MONTH));
        annio = Integer.toString(c.get(Calendar.YEAR));
        txtFecha.setText(dia + "-" + mes + "-" + annio);
        String hora = Integer.toString((c.get(Calendar.HOUR)));
        String min = Integer.toString((c.get(Calendar.MINUTE)));
        String mer = Integer.toString((c.get(Calendar.AM_PM)));
        String Meridiano = "AM";
        if (mer.equals("1")) {
            Meridiano = "PM";
        }
        txtHora.setText(hora + ":" + min + " " + Meridiano);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtHora;
    public static javax.swing.JLabel txtPropietario;
    private javax.swing.JTextArea txtReporte;
    private javax.swing.JTextField txtVehiculo;
    // End of variables declaration//GEN-END:variables
}
