package gonacmecanico;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Conector;

public class altaCamion extends javax.swing.JFrame {

    // Se instancia una conexion de la clase conecta
    Conector con = new Conector();
    // se asigna la conexion a la base de datos con la variable cn
    Connection cn = con.conecta();

    String Activo = "no";
    DefaultTableModel modelo;

    public altaCamion() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicio();
        mostrarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlNombre = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        jlUsuario = new javax.swing.JLabel();
        jlPaterno = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jlMaterno = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jlMunicipio = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jlColonia = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jlCelular = new javax.swing.JLabel();
        txtMotor = new javax.swing.JTextField();
        txtPropiedad = new javax.swing.JTextField();
        jlEmail = new javax.swing.JLabel();
        chkActivo = new javax.swing.JCheckBox();
        txtId = new javax.swing.JLabel();
        jlTipoPlaca = new javax.swing.JLabel();
        txtTipoPlaca = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administración de Vehículos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/salir.png"))); // NOI18N
        jbSalir.setText("SALIR");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/camion.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/agregar.png"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/eliminar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/modificar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnGrabar)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(jbSalir)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnNuevo)
                .addComponent(btnGrabar)
                .addComponent(btnEditar)
                .addComponent(btnActualizar))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbSalir)
                .addComponent(btnCancelar))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNombre.setText("Numero");

        jlUsuario.setText("Placa");

        jlPaterno.setText("Tipo");

        jlMaterno.setText("Marca");

        jlMunicipio.setText("Serie");

        jlColonia.setText("Modelo");

        jlCelular.setText("Motor");

        jlEmail.setText("Propiedad");

        chkActivo.setText("Activo");

        jlTipoPlaca.setText("Tipo Placa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlTipoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCelular))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMotor)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 3, Short.MAX_VALUE)))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTipoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkActivo)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jlEmail)
                                .addGap(106, 106, 106)
                                .addComponent(txtPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNombre)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPaterno))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlMaterno)
                            .addComponent(jlCelular)
                            .addComponent(txtMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlMunicipio)
                            .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlColonia))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUsuario)
                    .addComponent(jlEmail)
                    .addComponent(txtPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkActivo)
                    .addComponent(txtId)
                    .addComponent(jlTipoPlaca)
                    .addComponent(txtTipoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        try {
            cn.close();
        } catch (SQLException ex) {
            Logger.getLogger(altaCamion.class.getName()).log(Level.SEVERE, null, ex);
        }
        Principal frm = new Principal();
        this.dispose();
        frm.setVisible(true);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        btnNuevo.setEnabled(false);
        btnGrabar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnCancelar.setEnabled(true);
        jlNombre.setEnabled(true);
        jlPaterno.setEnabled(true);
        jlMaterno.setEnabled(true);
        jlUsuario.setEnabled(true);
        jlMunicipio.setEnabled(true);
        jlColonia.setEnabled(true);
        jlCelular.setEnabled(true);
        jlEmail.setEnabled(true);
        jlTipoPlaca.setEnabled(true);
        txtNumero.setEnabled(true);  
        txtTipo.setEnabled(true);
        txtMarca.setEnabled(true);
        txtPlaca.setEnabled(true);
        txtTipoPlaca.setEnabled(true);
        txtSerie.setEnabled(true);
        txtModelo.setEnabled(true);
        txtMotor.setEnabled(true);
        txtPropiedad.setEnabled(true);
        
        
        
        

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        if (txtNumero.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta el numero de la Unidad");
            txtNumero.requestFocus();
        }else if (txtTipo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta el tipo de la unidad");
            txtTipo.requestFocus();
        }else if (txtMarca.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta la marca de la unidad");
            txtMarca.requestFocus();
        }else if (txtPlaca.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta la placa de la Unidad");
            txtPlaca.requestFocus();
        }else if (txtTipoPlaca.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta el tipo de placa de la Unidad");
            txtTipoPlaca.requestFocus();
        }else if (txtSerie.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta el numero de Serie");
            txtSerie.requestFocus();
        }else if (txtModelo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta el Modelo");
            txtModelo.requestFocus();
        }else if (txtMotor.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta el numero de Motor");
            txtMotor.requestFocus();
        }else if (txtPropiedad.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta el Propietario");
            txtPropiedad.requestFocus();
        }else {
        
        String numero=txtNumero.getText();
        String tipo=txtTipo.getText();
        String marca=txtMarca.getText();
        String placa=txtPlaca.getText();
        String tipoPlaca=txtTipoPlaca.getText();
        String serie=txtSerie.getText();
        String modelo=txtModelo.getText();
        String motor=txtMotor.getText();
        String propiedad=txtPropiedad.getText();
        String activo="si";
        int contador=0;
        
        try {
                // revisamos si no hay un nombre o un usario ya en la bd con los mismos datos
                String sql="SELECT * FROM vehiculo WHERE numero='"+numero+
                        "' or serie='"+serie+"' or motor='"+motor+"'";
                Statement st;
                st = cn.createStatement();
                ResultSet rs=st.executeQuery(sql);
               
                while (rs.next()){
                    JOptionPane.showMessageDialog(null,"El vehiculo esta repetido en la base de datos");
                    contador++;
                    
                }
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(altaPersonal.class.getName()).log(Level.SEVERE, null, ex);
            }
        if (contador==0){
            try {
            //se prepara a insertarlo en la tabla de usuarios   
            Statement insertar=cn.createStatement();
            String sql="INSERT INTO vehiculo (numero,tipo,marca,placa,tipo_placa,serie,modelo,motor,propiedad) VALUES ('"+
                    numero+"','"+
                    tipo+"','"+
                    marca+"','"+
                    placa+"','"+
                    tipoPlaca+"','"+
                    serie+"','"+
                    modelo+"','"+
                    motor+"','"+
                    propiedad+"','"+
                    activo+"')";
                    
            insertar.executeUpdate(sql);
            insertar.close();
            
            
            
            JOptionPane.showMessageDialog(this,"se agregado el nuevo vehiculo");
            mostrarTabla();
            inicio();
            limpiar();
            
                       } catch (SQLException ex) {
            Logger.getLogger(altaPersonal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        int fila = tabla.getSelectedRow();
        
       if (fila>=0){
        btnNuevo.setEnabled(false);
        btnGrabar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnActualizar.setEnabled(true);
        btnCancelar.setEnabled(true);
        txtId.setVisible(false);
        jlNombre.setEnabled(true);
        jlPaterno.setEnabled(true);
        jlMaterno.setEnabled(true);
        jlUsuario.setEnabled(true);
        jlMunicipio.setEnabled(true);
        jlColonia.setEnabled(true);
        jlCelular.setEnabled(true);
        jlEmail.setEnabled(true);
        jlTipoPlaca.setEnabled(true);
        txtNumero.setEnabled(true);  
        txtTipo.setEnabled(true);
        txtMarca.setEnabled(true);
        txtPlaca.setEnabled(true);
        txtTipoPlaca.setEnabled(true);
        txtSerie.setEnabled(false);
        txtModelo.setEnabled(true);
        txtMotor.setEnabled(true);
        txtPropiedad.setEnabled(true);
        chkActivo.setEnabled(true);
           try {
               String id=tabla.getValueAt(fila, 0).toString();
               String sql="SELECT * FROM vehiculo where idUnidad='"+id+"'";
               Statement st;
               st=cn.createStatement();
               ResultSet rs=st.executeQuery(sql);
               while (rs.next()){
                   txtId.setText(rs.getString("idUnidad"));
                   
                    txtNumero.setText(rs.getString("numero"));
                   txtTipo.setText(rs.getString("tipo"));
                   txtMarca.setText(rs.getString("marca"));
                   txtPlaca.setText(rs.getString("placa"));
                   txtTipoPlaca.setText(rs.getString("tipo_placa"));
                   txtSerie.setText(rs.getString("serie"));
                   txtModelo.setText(rs.getString("modelo"));
                   txtMotor.setText(rs.getString("motor"));
                   txtPropiedad.setText(rs.getString("propiedad"));
                   
               }
               
           } catch (SQLException ex) {
               Logger.getLogger(altaCamion.class.getName()).log(Level.SEVERE, null, ex);
           }
       }else{
          JOptionPane.showMessageDialog(this,"Selecciona un elemento de la tabla"); 
       }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       inicio();
       limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
if (txtNumero.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta el numero de la Unidad");
            txtNumero.requestFocus();
        }else if (txtTipo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta el tipo de la unidad");
            txtTipo.requestFocus();
        }else if (txtMarca.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta la marca de la unidad");
            txtMarca.requestFocus();
        }else if (txtPlaca.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta la placa de la Unidad");
            txtPlaca.requestFocus();
        }else if (txtTipoPlaca.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta el tipo de placa de la Unidad");
            txtTipoPlaca.requestFocus();
        }else if (txtSerie.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta numero de serie");
            txtSerie.requestFocus();
        }else if (txtModelo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta el modelo");
            txtModelo.requestFocus();
        }else if (txtMotor.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta el numero de motor");
            txtMotor.requestFocus();
        }else if (txtPropiedad.getText().equals("")){
            JOptionPane.showMessageDialog(this, "falta el propietario");
            txtPropiedad.requestFocus();
        }else {
        String id=txtId.getText();
        String tipo=txtTipo.getText();
        String marca=txtMarca.getText();
        String placa=txtPlaca.getText();
        String tipoPlaca=txtTipoPlaca.getText();
        String serie=txtSerie.getText();
        String modelo=txtModelo.getText();
        String motor=txtMotor.getText();
        String propiedad=txtPropiedad.getText();
        String activo="no";
        if (chkActivo.isSelected()){
            activo="si";
        }
        
            try {
            Statement st;
            st=cn.createStatement();
            String sql="UPDATE vehiculo SET motor='"+motor+"',tipo='"+tipo+"',"+
                    "marca='"+marca+"',propiedad='"+propiedad+"',placa='"+placa+"',tipo_placa='"+tipoPlaca+"',"
                    + "serie='"+serie+"',modelo='"+modelo+"',activo='"+activo+"' WHERE idUnidad='"+id+"'";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Vehiculo actualizado");
            inicio();
            limpiar();
            mostrarTabla();
           } catch (SQLException ex) {
               Logger.getLogger(altaCamion.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(altaCamion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(altaCamion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(altaCamion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(altaCamion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new altaCamion().setVisible(true);

            }
        });
    }

    void mostrarTabla() {
        String[] cabecera = {"Id", "Numero", "Tipo", "Marca", "Placa","Tipo/placa", "Serie","Modelo","Act."};
        String[] registros = new String[9];
        String sql = "SELECT * FROM vehiculo";
        //establecemos los anchos en pixeles de las columnas
        int[] anchos = {0, 70, 110, 100, 70, 80, 140,100,30};

        modelo = new DefaultTableModel(null, cabecera);
        try {

            Statement table;
            table = cn.createStatement();
            ResultSet rs = table.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("idUnidad");
                registros[1] = rs.getString("numero");
                registros[2] = rs.getString("tipo");
                registros[3] = rs.getString("marca");
                registros[4] = rs.getString("placa");
                registros[5] = rs.getString("tipo_placa");
                registros[6] = rs.getString("serie");
                registros[7] = rs.getString("modelo");
                registros[8] = rs.getString("activo");

                modelo.addRow(registros);

            }
            tabla.setModel(modelo);
            for (int i = 0; i < cabecera.length; i++) {
                tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                tabla.setFont(new java.awt.Font("Tahoma", 0, 12));
            }
            tabla.getColumnModel().getColumn(0).setMaxWidth(0);
        tabla.getColumnModel().getColumn(0).setMinWidth(0);
        tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
        } catch (SQLException ex) {
            System.out.println("Sin poder ejecutar el query a la tabla");
        }

    }

    void inicio() {
        btnNuevo.setEnabled(true);
        btnGrabar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnEditar.setEnabled(true);
        btnActualizar.setEnabled(false);
        jlNombre.setEnabled(false);
        jlPaterno.setEnabled(false);
        jlMaterno.setEnabled(false);
        jlUsuario.setEnabled(false);
        jlMunicipio.setEnabled(false);
        jlColonia.setEnabled(false);
        jlCelular.setEnabled(false);
        jlEmail.setEnabled(false);
        jlTipoPlaca.setEnabled(false);
        txtNumero.setEnabled(false);  
        txtTipo.setEnabled(false);
        txtMarca.setEnabled(false);
        txtPlaca.setEnabled(false);
        txtTipoPlaca.setEnabled(false);
        txtSerie.setEnabled(false);
        txtModelo.setEnabled(false);
        txtMotor.setEnabled(false);
        txtPropiedad.setEnabled(false);
        chkActivo.setEnabled(false);

    }

    void limpiar(){
        txtNumero.setText("");  
        txtTipo.setText("");
        txtMarca.setText("");
        txtPlaca.setText("");
        txtTipoPlaca.setText("");
        txtSerie.setText("");
        txtModelo.setText("");

        txtMotor.setText("");

        txtPropiedad.setText("");

    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlCelular;
    private javax.swing.JLabel jlColonia;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlMaterno;
    private javax.swing.JLabel jlMunicipio;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlPaterno;
    private javax.swing.JLabel jlTipoPlaca;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtMotor;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPropiedad;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTipoPlaca;
    // End of variables declaration//GEN-END:variables
}
